name: acme-tests
on: [push, pull_request, workflow_dispatch]

jobs:
  run-acme-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image: ["python:3.8", "python:3.9"]
    steps:
    - name: Checkout acme
      uses: actions/checkout@v2
    - name: Run tests in docker
      run: |
        docker run --mount "type=bind,src=$(pwd),dst=/tmp/acme" \
            -w "/tmp/acme" --rm ${{ matrix.docker-image }} /bin/bash test.sh

